name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run all benchmarks
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            mode: instrumentation
          - runs-on: codspeed-macro
            mode: walltime
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Build the benchmark target
        run: |
          mkdir build
          cd build
          cmake -DCODSPEED_MODE=${{ matrix.mode }} ..
          cmake --build . -j

      - name: Run all benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: cd build && make run_all_benchmarks
          token: ${{ secrets.CODSPEED_TOKEN }}
