name: CodSpeed Benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run all benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Build the benchmark target
        run: |
          mkdir build
          cd build
          cmake -DCODSPEED_MODE=instrumentation ..
          make -j

      - name: Run all benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v3
        with:
          run: build/boost_bench # Path to our executable
          token: ${{ secrets.CODSPEED_TOKEN }}
          # No filter - run all benchmarks